### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: 猫咪锁屏--每天将待办任务展示到壁纸上
email: 564095922@qq.com
description: 全自动化管理规划您的日程
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.miaomiaolock.com" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
github_username:  sandoche
author: Sandoche Adittane
logo: assets/images/large-logo.png
social:
  name: 猫咪锁屏微博
  links:
    - https://weibo.com/u/2325532315

languages: ["cn"]
ampdir: amp


### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
