name: 猫咪锁屏
description: A super tagline for the mobile app
full_description: '每天将待办任务展示到壁纸上<br>
<br>关于我们:
<br>- 苹果官方「新鲜 App」推荐。
<br>- 苹果官方「编辑推荐」App。
<br>- 每天改变一点，做更好的自己。'
iOS: https://apps.apple.com/cn/app/id1555931775
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
